services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  storage:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio-data:/data
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: development
      API_HOST: 0.0.0.0
      API_PORT: 4545
      MINIO_HOST: storage
      MINIO_PORT: 9000
      DATABASE_URL: postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432/${POSTGRESQL_DB}?schema=public
    ports:
      - "4545:4545"
    depends_on:
      - db
      - storage
      - redis
    restart: unless-stopped


volumes:
  db-data:
  minio-data: